### ISSUE TITLE
Sky Modeling needs dynamic setting

### ISSUE THREAD

**Issue by prappleizer** [pysersic/pysersic#1]
we currently have hard-coded priors for dealing with sky backgrounds; these should be bootstrapped off the image somehow.

**Comment by tbmiller-astro** [comment]
In the previous commit the prior can now be accessed using the same `.set_prior()` class method but still need to add dynamic calculation

**Comment by prappleizer** [comment]
This might be a good place to also just use the astropy thing

**Comment by tbmiller-astro** [comment]
Fixed in #22
