### ISSUE TITLE
Naming of fitting and sampling methods

### ISSUE THREAD

**Issue by tbmiller-astro** [pysersic/pysersic#10]
Okay so currently there are 3 hard-coded fitting/sampling methods:

`.best_fit()`: finds the maximum a-posteriori and then assumes the posterior is Gaussian shaped withthe covariance calculated using the Laplace Approximation, i.e. using the hessian of the log-posterior, similar to Fisher Information stuff

`.train_flow()`: Performs inference using variational inference by optimizing a normalizing flow such that it best matches the posterior. then samples are drawn directly from this flow.

these first two call the internal `._train_svi()` method but with different set ups.

`.sample()`: NUTS sampler, by default 2 chains with 1000 warmup and 1000 inference steps.

The sampling one is pretty straightforward I think and is named well but what about the other two? The best fit one is a little ambiguous because it does produce a posterior but not sure how to differentiate it from the " traditional " SVI using the flow.

**Comment by tbmiller-astro** [comment]
I like that idea because then we could also write a `find_map()` function to just return a MAP estimate with no posterior which might be useful in some cases

**Comment by prappleizer** [comment]
Yeah, agreed!

**Comment by prappleizer** [comment]
that nicely splits the use cases into 
- give me MAP parameters alone (fastest, pure gal fit replacement) 
- give me an estimated posterior very quickly,
- give me a real posterior after actually sampling (longest, most accurate)
