### ISSUE TITLE
Some issues with current autoprior

### ISSUE THREAD

**Issue by tbmiller-astro** [pysersic/pysersic#19]
A few issues I have noticed with the current autoprior implementation:

1) For very small faint things the current estimate of half-light radii, which I think is based on like the second moment of the image, way over estimates the radii - Maybe we should use the kron radii instead.

2) Again for faint things the flux is negative and the rms is then nan, I'll add a simple thing now to absolute value but maybe there is something better we can be doing?

**Comment by prappleizer** [comment]
1. We can try kron radius; it also wasn't great for some galaxies I was testing on. For the faint ones does it stuck get the flux right? (is the flux measurement relatively ok?) if so we could default to something like a small prior for very faint things, or something in that vein?

2. abs value should be ok I think.... but I'll consider if there's anything better.

**Comment by tbmiller-astro** [comment]
Ya, I'm not sure what was going wrong exactly for the faint things, maybe it is the sky background? maybe related to #1.

**Comment by tbmiller-astro** [comment]
Fixed with #22
