### ISSUE TITLE
Error when using "fitter.sampling_results.get_chains()"

### ISSUE THREAD

**Issue by aruba19th** [pysersic/pysersic#26]
I am using pysersic version 0.1.2 and arviz version 0.12.1 . I ran into "AttributeError: module 'arviz' has no attribute 'extract'" when trying to read out chain info of sampling results by using "fitter.sampling_results.get_chains()".

I am wondering if this could be a version issue of arviz? 0.12.1 is pretty much the newest version available in pip installation but i do notice that there seems to be a newer version 0.14/0.16 around that is not maybe supported by pip yet.

**Comment by prappleizer** [comment]
@aruba19th for now please do just upgrade your Arviz to the development version; this should in theory fix your issue.

**Comment by aruba19th** [comment]
Sure, I'll try that!

**Comment by prappleizer** [comment]
HI @aruba19th. You actually shouldn't need to go to the development version. The pip version currently available is 0.16.0, not  0.12.1. See: [https://pypi.org/project/arviz/](https://pypi.org/project/arviz/). If you try ```pip install --upgrade arviz``` hopefully this will resolve that issue. I'm going to close this for now given the internal consistency between the required version and pip version, but am happy to help you get that sorted if you're having any trouble.

**Comment by aruba19th** [comment]
@prappleizer Oh, it turns out my Python version is too outdated and that's why I couldn't get any version beyond 0.12 for arviz via pip. This shouldn't be a problem once I get things upgraded. Thanks for your help!
