### ISSUE TITLE
JOSS Review: In Progress

### ISSUE THREAD

**Issue by AstroBarker** [pysersic/pysersic#28]
Hi folks! Making this issue to document my JOSS review https://github.com/openjournals/joss-reviews/issues/5703.

Working through this now -- some initial thoughts. The paper is really well written and describes appropriately the need and novelty of the software. A couple of small things, which can be ignored: the acronyms "PPL" and "HMC" are defined, but never used again. It is fine to just remove the acronyms.

I'm currently working through the [Fitting a single source](https://pysersic.readthedocs.io/en/latest/example-fit.html) example, and have run into some issues with `jax` -- when trying to construct the `FitSingle` fitter, it complains about non-numeric data:

`
TypeError: Dtype >f8 is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
`
This was accomplished with the following code:
```
#!/usr/bin/env python3

import numpy as np

from pysersic.priors import autoprior
from pysersic.results import plot_image
from pysersic import check_input_data
from pysersic import FitSingle
from pysersic.loss import student_t_loss

def load_data(n):
    im = np.load(f'examp_gals/gal{n}_im.npy')
    mask = np.load(f'examp_gals/gal{n}_mask.npy')
    sig = np.load(f'examp_gals/gal{n}_sig.npy')
    psf = np.load(f'examp_gals/gal{n}_psf.npy')
    return im,mask,sig,psf

im,mask,sig,psf = load_data(2)
check_input_data(data=im,rms=sig,psf=psf,mask=mask)

#fig, ax = plot_image(im,mask,sig,psf)
#fig.savefig('out.png')

prior  = autoprior(image = im, profile_type = 'sersic', mask=mask, sky_type = 'none')

#print( prior )

fitter = FitSingle(data=im,rms=sig,mask=mask,psf=psf,prior=prior,loss_func=student_t_loss)
```
The same happens when trying to construct a `FitMulti`. Perhaps I have missed something? Or some functionality has changed with versions? The conda environment I am using is below:
`environment.yml`:
```
name: pysersic
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.11
  - pip
  - arviz
  - asdf
  - astropy
  - corner
  - jax
  - matplotlib
  - numpy
  - numpyro
  - pandas
  - photutils
  - sep
  - scipy
  - tqdm
  - pip:
      - pysersic
```
Everything prior to constructing the fitter seemed to work as intended. Please let me know what you think.

Additional comments:
 - Please note the location of the example data in the documentation.
 - I would highly suggest including a minimally working environment that is guaranteed to work from publication time. Feel free to use the one I have created above (once any potential issues with versions are resolved).
 
 I will continue with my review and add additional thoughts below.

**Comment by prappleizer** [comment]
Hi @AstroBarker! Somehow, Tim and I never ran into this, but some of our early users have; I imagine something changed in Jax. The hot fix is to set the dtype of the offending array to float32 (or 64). In this case I believe it is the psf image that for some reason is saved f8. 

I'll make a PR to address this soon and coerce input images to a usable dtype within the fitter, but this fix should get you going further into the examples in the meantime.

**Comment by prappleizer** [comment]
The branch `dtype-coerce` now has the needed fix; feel free to check it out. It is ready for a PR as well ([see here](https://github.com/pysersic/pysersic/pull/29)) so as soon as tests have run and Tim takes a look we can merge that.

**Comment by AstroBarker** [comment]
Ah yeah, that did the trick. Thanks for the quick turnaround!

**Comment by AstroBarker** [comment]
A couple more minor notes. In the first code block of third example, there is a missing `import matplotlib.pyplot as plt`. Also, I noticed that the source extractor package `sep` is used. This should be listed along with the dependencies or otherwise documented somewhere. I've added it to the conda environment above.
Lastly, it would be beneficial to mention, perhaps alongside installation, that the user can test the software with `pytest` and that these tests are automatically run on all PRs.

I think that about covers it for my review... great work here! All of my points are minor and non-blocking and I'll wrap up my stuf fon the JOSS side. The only thing I feel strongly about is including, somewhere, (ideally both in the repo and the installation docs) a minimally working environment, for future-proofing. It will protect future users from potentially breaking changes that might get pushed into the dependencies.
Cheers!

**Comment by tbmiller-astro** [comment]
Thanks @AstroBarker  These are great suggestions, working on them now. Apologies, accidentally closed the issues with the PR. Re-opening now

**Comment by JBorrow** [comment]
I also had the issue with the incorrect type. Has that now been remedied?

**Comment by prappleizer** [comment]
@JBorrow It has been remedied in the current `main` build here on GitHub, but is not propagated to `pypi` yet. I'm updating descriptions and `pyproject.toml` now and should have a new version on pip tonight, so feel free to either install from GitHub or wait until tomorrow to upgrade with pip!

**Comment by prappleizer** [comment]
@AstroBarker We've added two environment files, one very similar to yours above, and one which has one arbitrary but working fully-specified versions for the dependencies that can be used if users are running into issues. PR #36 adds them along with some text in the readme and readthedocs which refers users to them at the install stage. That PR also has instructions for running the test suite.
