### ISSUE TITLE
Type error when using PySersicMultiPrior

### ISSUE THREAD

**Issue by aruba19th** [pysersic/pysersic#38]
I was trying to use the multiprior as demonstrated in the demo (so I basically copied all the code there and did a little modification) with my own data. A catalog was generated by SEP and to be fed into the multiprior object. But when I run the line `mp = PySersicMultiPrior(catalog = to_pysersic, sky_type='flat',sky_guess=sky_guess,sky_guess_err=sky_guess_err)`, a type error pops up:"'<class 'jaxlib.xla_extension.DeviceArray'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html"
And the error seems buried pretty deep. I am not sure if there's actually a bug or if my input data has some kind of non-compatible format/bit issue. (But I never had this problem if I use a single custom prior on the same data) I can attach my input data here if that would help.

**Comment by prappleizer** [comment]
Hi @aruba19th , definitely interesting, I haven't run into that with any multi-priors before. It could definitely be a change in jax, which is changing quickly, but I'm happy to take a look. Would you mind emailing me a little zip file of the image you are trying to fit and a notebook replicating the error?
