### ISSUE TITLE
The unit of intensity

### ISSUE THREAD

**Issue by Firestar-Reimu** [pysersic/pysersic#43]
I want to know if you use:

1. `mag/arcsec^2`/`mag/pixel^2` (with `-2.5log`)
2. `W/m^2/sr` (without `-2.5log`)

for $I(r)$ in Sersic profile:

$$
I(r) = I(0)\exp(r/r_0)^{1/4}
$$

**Comment by prappleizer** [comment]
You can see the exact equation used when we say "sersic" here: [https://github.com/pysersic/pysersic/blob/main/pysersic/rendering.py#L716](https://github.com/pysersic/pysersic/blob/main/pysersic/rendering.py#L716)

You can see that our amplitude normalization is tied to the *total flux* (note: some define the reference point as the flux at $r_e$, we do not).  Also note that we do not require (or assert) that the pixel units of the input image be "real" in any sense, and we do not carry out any internal conversions -- you will get out a model that fits the pixel counts in a given image, whether your pixels have been zero-pointed to real units or not.
