### ISSUE TITLE
Theta convention?

### ISSUE THREAD

**Issue by prappleizer** [pysersic/pysersic#49]
It appears to me that the current convention for theta in the fits is as measured from horizontal (to the right). This might confuse some astronomers who assume that theta will be measured from up to the left in the image (despite us not having or caring out WCS). Given the conventions, we could simply add +90 to the theta outputs, I believe, and this would then square with the PA expected by astronomers if they are using images with north up east left.

**Comment by tbmiller-astro** [comment]
Ya this would be easily doable. Maybe better to just highlight this somewhere in the docs and then keep the WCS agnostic orientation we have now. The vast majority of people will probably be using WCS aligned images but maybe better to leave as is. I'm not sure.

**Comment by prappleizer** [comment]
I definitely think we stay wcs agnostic. But in terms of an otherwise arbitrary convention (this is basically the same as the math vs physics debate over r/phi/theta), I think quoting theta from straight up, counterclockwise, is more intuitive to our users than measure from to the right. Particularly just to avoid confusion --- for random, non wcs images, having a convention of counterclockwise measured from north is equally good as counterclockwise measured from right. But for anyone who inserts an image for which they already know the rough PA in their head (visually, or from another code fit), their ability to quickly compare pysersic outputs to their internal intuition will be much better if we use north up. (and or it will prevent them thinking that pysersic was just wrong)?
