### ISSUE TITLE
Sersic profiles are really annoying

### ISSUE THREAD

**Issue by tbmiller-astro** [pysersic/pysersic#5]
Okay I've been trying all day to figure out how to accurately render Sersic profiles in the Fourier domain. I _think_ the main issue is that the Gaussian components cannot capture then inner steep bit so they tend to underestimate the flux by 3-5% for high n profiles. 

Possible solutions I've thought of:

1) Re-scale all of the amplitudes of the components to make sure the sum matches the input flux. I don't super like this solution as it artificially inflates the whole profile when the issue is really in the center.

2) Go with some 'softened' profile which mellows out in the center. This was done in SDSS (the luv and lux profiles) and maybe also in tractor. Its a decent option but then we have to make sure the definitions are consistent with "traditional" Sersic profiles that most people will expect.

3) a "hack" that I have implemented now. Basically calculate the expected flux at r < smallest width and adds it back into the amplitude of the smallest component. This essentially boosts it's flux to account for the potential of missing flux. This works okay, total fluxes for n=4 profiles are accurate to within 2% in the tests, but is a little hacky and we will have to test further. I like it cause it attempts to directly address the problem using reasonable assumptions that can be calculated on the fly.

Anyways mostly just venting and definitely open to suggestions

**Comment by tbmiller-astro** [comment]
Okay plot twist, after some further testing, the issues actually seemed to be with the outer profiles. I extended the default width of the largest Gaussian component (from 10*r_eff to 15*r_eff) and that seems to help. This is probably a little bit overkill for most cases, as the profiles as this large radii would be far below the noise level. 

Running a few more tests but all 3 renderers seem to agree now with ~2.5% on the total flux

**Comment by prappleizer** [comment]
Was this resolved in the recent update where users specify he largest component in real space?

**Comment by tbmiller-astro** [comment]
Yes that helps! All 3 renderers are now consistent within 2.5% accurate fluxes in all the tests. The real and hybrid renders are even more accurate than that. I think it's fine to close for now but good to keep an eye on
