### ISSUE TITLE
ValueError: StudentT distribution got invalid scale parameter.

### ISSUE THREAD

**Issue by ke27whal** [pysersic/pysersic#58]
Hello,

I'm trying to run pysersic on some modeled galaxies, and all of my inputs pass the check_input test, but I'm getting thrown an error saying that my loss function is getting an invalid scale parameter.

For reference, 
```
import numpy as np
from astropy.modeling.models import Sersic2D
from astropy.convolution import convolve, convolve_fft
import pysersic
from pysersic import FitSingle
from pysersic.loss import student_t_loss
from astropy.stats import sigma_clipped_stats

px_axis = np.linspace(-14,14,29)
x_px, y_px = np.meshgrid(px_axis, px_axis)

im_f = Sersic2D(amplitude=1, 10, n=4, x_0=0, y_0=0) ### should be in px
im = im_f(x_px, y_px) 

noise = np.random.normal(1e-3*max(np.ndarray.flatten(im)), size=im.shape)
im_noisy = im + noise

rms_im = im_noisy/30 + np.random.normal(im_noisy/50,size=im.shape)

print(check_input_data(data=im_noisy,rms=rms_im,psf=psf))

sky_med, sky_std, n_pix = estimate_sky(image=im_noisy)
sky_med_unc = sky_std/np.sqrt(n_pix) # Error on the median sky estimate

print(sky_med)
    
#### Priors
    
    
custom_prior = PySersicSourcePrior(profile_type='sersic', sky_type= 'flat', sky_guess=sky_med, sky_guess_err= 2*sky_med_unc)
    
custom_prior.set_uniform_prior('xc', 12.,17.)
custom_prior.set_uniform_prior('yc', 12.,17.)
    
custom_prior.set_uniform_prior('flux', 0.01, 10000)
custom_prior.set_uniform_prior('r_eff', 1,500.)
custom_prior.set_uniform_prior('ellip', 0, 1)
custom_prior.set_uniform_prior('theta', 0., 2*np.pi)
custom_prior.set_uniform_prior('n', 4,4)
    
### set up fitter
fitter = FitSingle(data=im_noisy,rms=rms_im,psf=psf,prior=custom_prior,loss_func=student_t_loss)
    
from jax.random import PRNGKey # Need to use a seed to start jax's random number generation
map_params = fitter.find_MAP(rkey = PRNGKey(1000))

fig, ax = plot_residual(im_noisy,map_params['model'], vmin=-0.2, vmax=.2)
```

Any ideas on how to fix this?

Best,
Kelly

**Comment by ke27whal** [comment]
I've been playing around with this a bit more, it's definitely an issue with my synthetic rms image. Is it just a bad mockup of what it should be for my synthetic data? Can pysersic run on modeled data?

**Comment by prappleizer** [comment]
Hi kelly, Yes, Pysersic can work on synthetic data; invalid loc and invalid scale, coming from jax, usually means something is off in the the way the priors are attempting to compare to the data (i.e., you choose a prior way off from the data, or you try to give the "scale" a negative number on a gaussian prior, etc). 

I am happy to play with a minimal working example a bit and let you know if i can quickly track down what might be going wrong in your priors setup; I'd need the psf you used (it's not created in the above example).

**Comment by ke27whal** [comment]
Great, thank you! Github doesn't support .npz files, but here is the psf.

`psf = np.array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.46040576e-05, 6.63933504e-05, 9.79144272e-05,
        1.07667689e-04, 1.15803467e-04, 1.51021554e-04, 1.51423175e-04,
        9.29427975e-05, 3.99288543e-05, 5.66499648e-05, 3.76360172e-05,
        9.91173712e-06, 5.48593764e-05, 3.28708436e-05, 4.52513552e-05,
        4.64015835e-05, 3.68685624e-05, 8.49785118e-05, 1.56564057e-04,
        1.57665342e-04, 1.14949445e-04, 8.24162636e-05, 7.51920103e-05,
        6.14157664e-05, 3.36545002e-05, 1.25715035e-05],
       [0.00000000e+00, 3.00108013e-05, 4.81092431e-05, 7.17956934e-05,
        7.71048040e-05, 1.00175720e-04, 1.78684689e-04, 2.26509313e-04,
        1.71652438e-04, 7.99060926e-05, 8.52195625e-05, 6.34432612e-05,
        5.85157328e-06, 2.55409035e-05, 3.59788714e-05, 1.14011096e-04,
        1.26304740e-04, 9.69864971e-05, 1.73627156e-04, 2.45806304e-04,
        1.93798672e-04, 1.08646389e-04, 6.32768664e-05, 5.12683855e-05,
        4.70348923e-05, 2.99656649e-05, 5.54100230e-06],
       [0.00000000e+00, 2.88057410e-05, 3.04731438e-05, 3.89005700e-05,
        4.13117896e-05, 7.69561987e-05, 1.92546695e-04, 3.03251535e-04,
        2.87145198e-04, 2.11133789e-04, 2.26371906e-04, 1.88849835e-04,
        5.82607247e-05, 4.41352125e-05, 1.09914213e-04, 2.79988115e-04,
        3.13870118e-04, 2.41525099e-04, 2.85783938e-04, 3.13530357e-04,
        1.98378145e-04, 8.25659158e-05, 5.11156111e-05, 5.03537548e-05,
        4.73586353e-05, 3.43858941e-05, 1.02535193e-05],
       [0.00000000e+00, 4.09770214e-05, 2.42176576e-05, 2.35717895e-05,
        2.22337700e-05, 6.01622484e-05, 1.86168985e-04, 3.22833036e-04,
        3.46395628e-04, 3.26030826e-04, 3.88634581e-04, 3.23071242e-04,
        1.20590904e-04, 6.84259480e-05, 1.81445757e-04, 4.36173257e-04,
        5.04350257e-04, 3.81769476e-04, 3.57237603e-04, 3.25913407e-04,
        1.78603064e-04, 7.17723231e-05, 5.41922386e-05, 5.31793939e-05,
        5.05932432e-05, 3.88469815e-05, 1.11776914e-05],
       [0.00000000e+00, 4.52768546e-05, 2.05706662e-05, 2.32764043e-05,
        3.31887317e-05, 7.14553923e-05, 1.88002765e-04, 3.15405196e-04,
        3.40555439e-04, 3.52302657e-04, 4.31758661e-04, 3.38624970e-04,
        1.21921768e-04, 7.53353453e-05, 1.73538603e-04, 4.32368148e-04,
        5.33415899e-04, 4.03497917e-04, 3.56716864e-04, 3.20091188e-04,
        1.84092287e-04, 9.21618703e-05, 6.80587868e-05, 5.41507900e-05,
        5.32318616e-05, 3.98427779e-05, 1.01071444e-05],
       [0.00000000e+00, 4.00263653e-05, 2.34378514e-05, 3.78428768e-05,
        5.91994995e-05, 1.18989383e-04, 2.63088946e-04, 3.85896309e-04,
        3.74989304e-04, 3.55845039e-04, 3.76616541e-04, 2.37931180e-04,
        9.83920644e-05, 1.20521115e-04, 9.11790194e-05, 2.60388196e-04,
        4.16659421e-04, 3.72415210e-04, 3.72372314e-04, 3.79269011e-04,
        2.59873541e-04, 1.36495938e-04, 8.02084205e-05, 5.09000946e-05,
        4.42954688e-05, 3.53543955e-05, 9.84479148e-06],
       [0.00000000e+00, 3.26798533e-05, 1.15008802e-05, 2.89253976e-05,
        5.79435997e-05, 1.23262367e-04, 2.80781428e-04, 4.10081457e-04,
        3.83594807e-04, 3.56971647e-04, 3.74188693e-04, 3.06569724e-04,
        4.31327698e-04, 6.01136275e-04, 3.56859600e-04, 2.32535293e-04,
        3.46066706e-04, 3.14927526e-04, 3.69573495e-04, 3.94419217e-04,
        2.69706992e-04, 1.28899615e-04, 6.11726919e-05, 3.89923035e-05,
        3.64873107e-05, 2.91671387e-05, 4.95982201e-06],
       [0.00000000e+00, 3.85541563e-05, 6.07925424e-06, 2.24855408e-05,
        4.26272683e-05, 7.37194131e-05, 1.63892877e-04, 2.30417350e-04,
        2.18597754e-04, 3.49532468e-04, 6.01705484e-04, 7.30475634e-04,
        1.43614424e-03, 1.83168816e-03, 1.34725960e-03, 7.67275421e-04,
        6.30593861e-04, 3.12008569e-04, 1.95805877e-04, 2.63778554e-04,
        1.51681502e-04, 5.65116072e-05, 3.78027323e-05, 3.18182326e-05,
        3.49173307e-05, 3.27213361e-05, 1.07467051e-05],
       [0.00000000e+00, 6.21074004e-05, 3.97224740e-05, 6.74767467e-05,
        1.11059571e-04, 9.53947267e-05, 6.39978817e-05, 7.30529500e-05,
        2.61401849e-04, 9.53192374e-04, 1.64049262e-03, 1.62048501e-03,
        2.46706088e-03, 3.24806770e-03, 2.27537903e-03, 1.72562912e-03,
        1.75496110e-03, 8.94003702e-04, 1.59015936e-04, 7.38397787e-05,
        8.14352853e-05, 1.00513686e-04, 1.08062055e-04, 7.49026552e-05,
        6.00475307e-05, 4.89267206e-05, 1.86916789e-05],
       [0.00000000e+00, 8.29840482e-05, 9.45024222e-05, 1.85061747e-04,
        3.09214194e-04, 2.89004969e-04, 1.68503414e-04, 2.17245426e-04,
        8.87434890e-04, 2.35365815e-03, 2.84237146e-03, 1.63180982e-03,
        3.96393110e-03, 6.17606521e-03, 3.53848336e-03, 1.55739830e-03,
        2.83606274e-03, 2.31642225e-03, 7.15912636e-04, 1.98188619e-04,
        1.72096263e-04, 2.73978522e-04, 2.80149773e-04, 1.62089229e-04,
        8.32030503e-05, 5.67302919e-05, 1.93825805e-05],
       [0.00000000e+00, 1.02690894e-04, 1.51677317e-04, 3.00653712e-04,
        4.91761688e-04, 4.93373623e-04, 3.60843320e-04, 4.75319692e-04,
        1.49024293e-03, 3.41482596e-03, 3.35117597e-03, 4.65017757e-03,
        1.53947679e-02, 2.30084061e-02, 1.50622520e-02, 4.13946068e-03,
        3.00579805e-03, 3.21709353e-03, 1.28106818e-03, 4.00303063e-04,
        3.15451458e-04, 4.28839844e-04, 4.15234155e-04, 2.41034557e-04,
        1.29694566e-04, 8.93548211e-05, 2.49379225e-05],
       [0.00000000e+00, 1.53984303e-04, 2.03674384e-04, 3.32835036e-04,
        5.25771951e-04, 5.52500361e-04, 4.30845455e-04, 5.50278899e-04,
        1.57983432e-03, 3.41262597e-03, 4.74806267e-03, 1.42949370e-02,
        4.13544932e-02, 5.86313219e-02, 4.18971948e-02, 1.39852006e-02,
        3.87651003e-03, 3.05372664e-03, 1.32810486e-03, 4.35679336e-04,
        3.73075607e-04, 4.59525939e-04, 4.37296517e-04, 2.98446102e-04,
        2.19615942e-04, 1.73552292e-04, 6.45365554e-05],
       [0.00000000e+00, 2.06901465e-04, 2.39152079e-04, 3.19563262e-04,
        4.78254355e-04, 4.95763555e-04, 4.18418554e-04, 5.18486987e-04,
        1.50046385e-03, 3.42807630e-03, 6.23479231e-03, 2.15953475e-02,
        5.86618710e-02, 8.18520690e-02, 5.98829459e-02, 2.19361308e-02,
        5.40846518e-03, 2.92135963e-03, 1.17074789e-03, 3.85409387e-04,
        3.67395981e-04, 4.25945555e-04, 3.99217845e-04, 2.89558393e-04,
        2.51769768e-04, 2.15058809e-04, 8.67039594e-05],
       [0.00000000e+00, 1.83155448e-04, 2.15857727e-04, 3.12440172e-04,
        4.65663191e-04, 4.80424449e-04, 4.00128503e-04, 5.56785618e-04,
        1.63430422e-03, 3.31489515e-03, 4.51152795e-03, 1.45554562e-02,
        4.23020458e-02, 6.00665135e-02, 4.31495948e-02, 1.45229275e-02,
        3.81634273e-03, 2.95657179e-03, 1.25146709e-03, 3.44853109e-04,
        3.45072763e-04, 4.37295025e-04, 4.02900561e-04, 2.62684424e-04,
        1.97488645e-04, 1.69644900e-04, 6.57580628e-05],
       [0.00000000e+00, 8.22364711e-05, 1.32782084e-04, 2.46092888e-04,
        4.00900885e-04, 3.89704172e-04, 2.72026729e-04, 4.13769061e-04,
        1.46747787e-03, 3.35092895e-03, 2.91680105e-03, 4.11821467e-03,
        1.49751987e-02, 2.26068284e-02, 1.47183569e-02, 3.61857161e-03,
        2.66995244e-03, 3.29704864e-03, 1.33143063e-03, 3.77291045e-04,
        3.04048592e-04, 4.04687820e-04, 3.89477438e-04, 2.26317728e-04,
        1.16638975e-04, 8.84631388e-05, 3.66837761e-05],
       [0.00000000e+00, 4.62996559e-05, 8.90800098e-05, 1.56226200e-04,
        2.48042689e-04, 2.21781402e-04, 1.22531809e-04, 1.98442185e-04,
        8.16144233e-04, 2.48198487e-03, 2.90542292e-03, 1.76374935e-03,
        3.96285305e-03, 5.89454120e-03, 3.38968397e-03, 1.44348252e-03,
        2.85472122e-03, 2.47704789e-03, 7.07517248e-04, 1.44990666e-04,
        1.61375689e-04, 2.50626667e-04, 2.58311263e-04, 1.45317051e-04,
        6.36095172e-05, 5.13403484e-05, 2.40983162e-05],
       [0.00000000e+00, 4.20960430e-05, 6.38448474e-05, 8.36667952e-05,
        1.02262833e-04, 9.33120398e-05, 8.88070195e-05, 8.85226173e-05,
        2.65499661e-04, 1.02243022e-03, 1.81724080e-03, 1.70922311e-03,
        2.60138294e-03, 3.32260973e-03, 2.33425878e-03, 1.64313005e-03,
        1.71404275e-03, 8.62012683e-04, 8.86932962e-05, 7.63450049e-05,
        8.02317979e-05, 7.88372884e-05, 9.03915492e-05, 5.40813744e-05,
        3.68858578e-05, 3.90565503e-05, 2.01839643e-05],
       [0.00000000e+00, 3.42741956e-05, 5.05188256e-05, 5.43184831e-05,
        5.06978917e-05, 8.38627850e-05, 1.84372908e-04, 2.63233739e-04,
        2.20206941e-04, 3.95231491e-04, 6.85804251e-04, 7.93556010e-04,
        1.39578804e-03, 1.94543349e-03, 1.35047543e-03, 7.80514828e-04,
        6.09358944e-04, 2.48072374e-04, 1.81888783e-04, 2.61816939e-04,
        1.65619615e-04, 6.99128488e-05, 3.47813018e-05, 2.62719979e-05,
        2.62068797e-05, 2.77046647e-05, 1.25388209e-05],
       [0.00000000e+00, 3.35364031e-05, 4.57026089e-05, 4.60562064e-05,
        6.00441053e-05, 1.43800775e-04, 3.10036388e-04, 4.57776837e-04,
        3.99397576e-04, 3.56912880e-04, 4.09717183e-04, 2.78993716e-04,
        3.77550295e-04, 6.18559281e-04, 3.93097840e-04, 3.10757719e-04,
        3.92431085e-04, 3.51127766e-04, 3.79856064e-04, 4.13040046e-04,
        3.04506909e-04, 1.54478212e-04, 6.85218791e-05, 3.20851148e-05,
        2.27847586e-05, 2.16200631e-05, 9.45665064e-06],
       [0.00000000e+00, 4.00117713e-05, 4.36375746e-05, 3.91366134e-05,
        6.14075330e-05, 1.31455674e-04, 3.02795981e-04, 4.47995561e-04,
        4.28749948e-04, 3.85347996e-04, 4.37189768e-04, 2.46991206e-04,
        9.21115972e-05, 1.34579694e-04, 1.40721806e-04, 3.08540245e-04,
        4.80485585e-04, 4.16594061e-04, 3.78138811e-04, 4.10521064e-04,
        3.04783858e-04, 1.53218106e-04, 7.56757123e-05, 3.41778858e-05,
        1.48606679e-05, 1.35007998e-05, 6.84274199e-06],
       [0.00000000e+00, 4.74259317e-05, 3.30887005e-05, 3.63452278e-05,
        4.49592665e-05, 7.45234651e-05, 2.07427959e-04, 3.62232881e-04,
        3.88024707e-04, 4.01334227e-04, 5.00865629e-04, 3.40803468e-04,
        9.70518293e-05, 8.87157935e-05, 2.06109744e-04, 4.36309954e-04,
        5.50384957e-04, 4.22984045e-04, 3.37992343e-04, 3.19157052e-04,
        1.95617376e-04, 9.13761765e-05, 6.22376559e-05, 4.20226564e-05,
        2.31907575e-05, 1.40022495e-05, 2.81839683e-06],
       [0.00000000e+00, 5.21789826e-05, 3.92565308e-05, 5.02402373e-05,
        5.95960773e-05, 7.24074788e-05, 1.74707729e-04, 3.17034885e-04,
        3.36387250e-04, 3.48380166e-04, 4.30418081e-04, 3.11968172e-04,
        9.88703144e-05, 1.01101454e-04, 2.08580694e-04, 3.94392966e-04,
        4.63524135e-04, 3.70332715e-04, 3.21550807e-04, 3.04883814e-04,
        1.77121339e-04, 7.72438565e-05, 6.66388943e-05, 5.99528397e-05,
        4.41962192e-05, 3.05309797e-05, 1.18320466e-05],
       [0.00000000e+00, 5.93750826e-05, 4.38855870e-05, 6.80705934e-05,
        7.93104277e-05, 9.95074934e-05, 2.03987042e-04, 3.01569765e-04,
        2.62660628e-04, 2.04346333e-04, 2.45187297e-04, 1.78931577e-04,
        5.97491066e-05, 7.26275602e-05, 1.16656973e-04, 2.11558601e-04,
        2.44405962e-04, 2.26616754e-04, 2.76380435e-04, 3.15553444e-04,
        2.10257052e-04, 9.26790478e-05, 7.09995227e-05, 6.22478753e-05,
        4.58707604e-05, 3.60259095e-05, 1.49800017e-05],
       [0.00000000e+00, 5.22223583e-05, 5.09036726e-05, 7.16633585e-05,
        7.92530152e-05, 1.16208258e-04, 2.04012183e-04, 2.39517001e-04,
        1.67511740e-04, 8.40343322e-05, 9.25075459e-05, 6.90477782e-05,
        2.90743734e-05, 5.52103848e-05, 5.45751463e-05, 8.56256739e-05,
        8.41077156e-05, 1.01597815e-04, 1.78862755e-04, 2.49104780e-04,
        1.99500355e-04, 1.00346031e-04, 6.57653954e-05, 4.90356835e-05,
        3.48540119e-05, 2.94497173e-05, 1.26240733e-05],
       [0.00000000e+00, 4.11198639e-05, 5.83776296e-05, 8.57121312e-05,
        9.21792848e-05, 1.14096214e-04, 1.55549930e-04, 1.52128989e-04,
        9.65657181e-05, 5.20581759e-05, 4.92001025e-05, 3.64537214e-05,
        2.75353016e-05, 4.54230248e-05, 3.37043054e-05, 4.29036671e-05,
        3.31686882e-05, 4.64049726e-05, 9.54792201e-05, 1.61865855e-04,
        1.53788467e-04, 9.65076768e-05, 6.34772677e-05, 4.10670884e-05,
        2.18071794e-05, 1.65845473e-05, 9.42211796e-06],
       [0.00000000e+00, 2.31233268e-05, 2.56761566e-05, 5.53487827e-05,
        5.17775720e-05, 4.86749194e-05, 6.10957645e-05, 4.72356866e-05,
        3.29437327e-05, 3.40150867e-05, 3.29933814e-05, 1.74546509e-05,
        1.76965087e-05, 1.70138271e-05, 1.09581281e-05, 2.00915384e-05,
        1.16717317e-05, 1.78011655e-05, 2.61404016e-05, 6.07289571e-05,
        6.39195452e-05, 4.13797296e-05, 3.20708754e-05, 1.88711558e-05,
        3.06632531e-06, 2.94372188e-06, 3.71542947e-06]])
`

**Comment by ke27whal** [comment]
I also realized I missed a line when condensing this snippet of code for github. Plese use this instead.

import numpy as np
from astropy.modeling.models import Sersic2D
from astropy.convolution import convolve, convolve_fft
import pysersic
from pysersic import FitSingle
from pysersic.loss import student_t_loss
from astropy.stats import sigma_clipped_stats

px_axis = np.linspace(-14,14,29)
x_px, y_px = np.meshgrid(px_axis, px_axis)

im_f = Sersic2D(amplitude=1, 10, n=4, x_0=0, y_0=0) ### should be in px
im = im_f(x_px, y_px) 

im_conv = convolve_fft(im, psf)

noise = np.random.normal(1e-3*max(np.ndarray.flatten(im_conv)), size=im_conv.shape)
im_noisy = im_conv + noise

rms_im = im_noisy/30 + np.random.normal(im_noisy/50,size=im.shape)

print(check_input_data(data=im_noisy,rms=rms_im,psf=psf))

sky_med, sky_std, n_pix = estimate_sky(image=im_noisy)
sky_med_unc = sky_std/np.sqrt(n_pix) # Error on the median sky estimate

print(sky_med)
    
#### Priors
    
    
custom_prior = PySersicSourcePrior(profile_type='sersic', sky_type= 'flat', sky_guess=sky_med, sky_guess_err= 2*sky_med_unc)
    
custom_prior.set_uniform_prior('xc', 12.,17.)
custom_prior.set_uniform_prior('yc', 12.,17.)
    
custom_prior.set_uniform_prior('flux', 0.01, 10000)
custom_prior.set_uniform_prior('r_eff', 1,500.)
custom_prior.set_uniform_prior('ellip', 0, 1)
custom_prior.set_uniform_prior('theta', 0., 2*np.pi)
custom_prior.set_uniform_prior('n', 4,4)
    
### set up fitter
fitter = FitSingle(data=im_noisy,rms=rms_im,psf=psf,prior=custom_prior,loss_func=student_t_loss)
    
from jax.random import PRNGKey # Need to use a seed to start jax's random number generation
map_params = fitter.find_MAP(rkey = PRNGKey(1000))

fig, ax = plot_residual(im_noisy,map_params['model'], vmin=-0.2, vmax=.2)

**Comment by prappleizer** [comment]
Hi Kelly, 

Thanks for the info! The issue did appear to be your `rms_im` --- pysersic expects this to be the uncertainty on each pixel, (i.e., 1/root(invar)), which by definition is positive valued. So the scale parameter was failing because the numpyro model couldn't interpret a "negative uncertainty", and your `rms_im` contains a distribution of pixel values centered near zero and extending both positive and negative. 

As a simple test I replaced your unc image with `np.ones(im_noisy.shape)*np.std(im_noisy)`, and had no trouble fitting. 

It's obviously best to use a real weight-map derived uncertainty image (i.e., including both the rms noise and the poisson noise of the image), but there are options for simulating this at least loosely; the main thing is to just be sure the values in your unc/rms image are >0! 

Hope this helps!

**Comment by prappleizer** [comment]
I've just updated the `check_input_data()` to raise an exception if the rms array contains negatives [here](https://github.com/pysersic/pysersic/commit/c2a54ceb3146a6f484b24c768c75b117ae1d04eb), so hopefully that should catch this kind of thing in the future :)

**Comment by ke27whal** [comment]
Thank you so much for all your help! :)
