### ISSUE TITLE
Does pysersic need a GAIN parameter?

### ISSUE THREAD

**Issue by WeichenStars** [pysersic/pysersic#61]
Hi everyone,

First, thank you for making this very nice tool openly available! I've found it easy and intuitive to use and quite robust with the MCMC machinery.

I have a naive question about the input setup: 

Do I need tell pysersic the GAIN value of my input image? I know it is needed for galfit and some other similar tools to properly account for the Poisson noise, but this doesn't seem to be the case for pysersic. How does pysersic know the pixel flux uncertainties, including the photon counting error for the light from the source to fit? Do all these uncertainties need to be combined as a single 2D array and be fed to the "rms" input argument?

A relevant question is, does the pixel unit of the input images/error images need to be something like electron/s (as needed for galfit) or it can be arbitrary?

Thanks in advance,
Weichen

**Comment by prappleizer** [comment]
Hi @WeichenStars! 

Yes, at the moment, `pysersic` relies on the input rms map as the pixel-by-pixel uncertainties while fitting, so well-characterized weight maps which include the poisson noise from the source as well as the rms noise of the background will provide the best results. Generally surveys will provide this for available imaging.

If a proper weight map doesn't exist, then one can in principle perform an exercise of fitting with a rms map of just the robust-measured background, which will provide a reasonable model for the galaxy; the poisson uncertainty for just the galaxy can then be estimated from that model, and a new rms map including both can be used to re-fit (this process can be done iteratively). 

We are actually thinking about ways to actually "fit" for the weight map while simultaneously fitting the parameters, but that's a roadmap feature and not yet supported. I'll also note that we do support a few alternate loss functions, e.g., `student_t_loss_free_sys` that aim to introduce an extra noise/jitter term in cases where the provided rms might not be well characterizing the galaxy. These have not been extensively tested, however. 

And to answer your last question, `pysersic` is entirely agnostic to the input units of the imaging, so long as the rms map is in the same units as the image; this is related to the lack of a gain parameter. In short, it's something galfit can estimate/bootstrap given that the gain is provided and the units are e/s, whereas we support any units but have the user supply the rms map appropriately.

**Comment by WeichenStars** [comment]
Got it, thanks for the answer! I will try the strategy as you recommended with the rms map.
