### ISSUE TITLE
Question About Units

### ISSUE THREAD

**Issue by nehirozden** [pysersic/pysersic#62]
Hello!

My name is Nehir and I have been using your code to do research on some UMGs, which has been great! Thanks for the amazing code. 

I just had a quick question about units, in which I tried looking at the docs and the code and couldn't find. Overall, when the corner plot is spit out for the sample results, what are the units for r_eff? I am assuming the the x & y are in pixels, but for everything else I am a bit unsure about. Is there anywhere in the docs that explain this that I am missing? 

Thank you again for the amazing program!

**Comment by prappleizer** [comment]
Hi @nehirozden, the units for `r_eff` is pixels, like x and y. To obtain the spatial `r_eff` in arcseconds you'll need to know the pixel scale of your image. The units of flux are the same as whatever the input image is, and theta is in radians in the nominal outputs. Ellipticity is the same as 1 - (b/a), so a circular fit (b/a=1) corresponds to an ellip of 0, and we don't generally fit beyond an ellip of ~0.9 or so. 

I'll add these notes on units to the docs; thanks for asking!
